In [1]:
import pandas as pd

In [2]:
# Dataset 1
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3],
    "Name": ["Devashish", "Mangesh", "Amit"]
})

# Dataset 2
orders = pd.DataFrame({
    "CustomerID": [1, 2, 4],
    "OrderAmount": [500, 700, 300]
})

In [3]:
#merge() (Most Important ⭐)
#Inner Merge
pd.merge(customers, orders, on="CustomerID")

   CustomerID       Name  OrderAmount
0           1  Devashish          500
1           2    Mangesh          700

In [4]:
#Left Merge
pd.merge(customers, orders, on="CustomerID", how="left")

   CustomerID       Name  OrderAmount
0           1  Devashish        500.0
1           2    Mangesh        700.0
2           3       Amit          NaN

In [5]:
#Right Merge
pd.merge(customers, orders, on="CustomerID", how="right")

   CustomerID       Name  OrderAmount
0           1  Devashish          500
1           2    Mangesh          700
2           4        NaN          300

In [6]:
#Outer Merge
pd.merge(customers, orders, on="CustomerID", how="outer")

   CustomerID       Name  OrderAmount
0           1  Devashish        500.0
1           2    Mangesh        700.0
2           3       Amit          NaN
3           4        NaN        300.0

In [11]:
#join()
customers.set_index("CustomerID").join(
    orders.set_index("CustomerID"),
    how="left"
)

                 Name  OrderAmount
CustomerID
1           Devashish        500.0
2             Mangesh        700.0
3                Amit          NaN